<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowDown, Bell, CircleCheckFilled, Clock, Connection, DataAnalysis, Files, Key, Lock, Menu, Operation, Plus, Refresh, Setting, User, UserFilled, WarningFilled } from '@element-plus/icons-vue'
import { api } from './api'
import { useSessionStore } from './stores/session'

type UserRow = { id: string; username: string; role: string; status: string; must_change_password: boolean; created_at: string; desired_config_version: number; applied_config_version: number; frp_credential: { present: boolean; secret_version: number; rotated_at?: string; status: string } }
type Stats = { active_users: number; mappings: number; pending: number; errors: number; server_uptime_seconds: number; frps_public_host: string; frps_public_port: number }
type ExternalResidue = { resource_type: string; resource_id: string; provider: string; identifier: string; reason: string; created_at: string; resolved_at?: string }
type Operation = { id: string; operation_type: string; status: string; phase: string; step: string; error_code?: string; error_message?: string; compensation_status?: string; external_residue_count?: number; external_residues?: ExternalResidue[]; created_at: string }

const session = useSessionStore()
const view = ref('overview')
const stats = ref<Stats>({ active_users: 0, mappings: 0, pending: 0, errors: 0, server_uptime_seconds: 0, frps_public_host: '', frps_public_port: 0 })
const users = ref<UserRow[]>([])
const selectedFRPUserID = ref('')
const operations = ref<Operation[]>([])
const loading = ref(false)
const loginForm = ref({ username: 'admin', password: '' })
const showAddress = ref(false)
const showCreateUser = ref(false)
const newUsername = ref('')
const initialPassword = ref('')
const cfStatus = ref<{ configured: boolean; status: string; token_version?: number; verified_at?: string; capabilities?: { missing?: string[] } }>({ configured: false, status: 'missing' })
const cfToken = ref('')
const clearCountdown = ref(0)
const nav = [
  { id: 'overview', label: '运行总览', kicker: 'CONTROL ROOM', icon: DataAnalysis },
  { id: 'users', label: '用户与会话', kicker: 'IDENTITY', icon: UserFilled },
  { id: 'operations', label: '操作队列', kicker: 'OPERATIONS', icon: Operation },
  { id: 'cloudflare', label: 'Cloudflare', kicker: 'EDGE PROVIDER', icon: Connection },
  { id: 'system', label: '系统边界', kicker: 'SYSTEM', icon: Setting }
]
const activeNav = computed(() => nav.find(item => item.id === view.value) ?? nav[0])
const selectedFRPUser = computed(() => users.value.find(item => item.id === selectedFRPUserID.value))

async function loadData() {
  if (!session.authenticated) return
  loading.value = true
  try {
    const [s, u, o, c] = await Promise.all([api<Stats>('/api/v1/admin/stats'), api<{ items: UserRow[] }>('/api/v1/admin/users'), api<{ items: Operation[] }>('/api/v1/admin/operations'), api<typeof cfStatus.value>('/api/v1/cloudflare/status')])
    stats.value = s; users.value = u.items; operations.value = o.items; cfStatus.value = c
  } catch (err) { ElMessage.error(err instanceof Error ? err.message : '数据加载失败') }
  finally { loading.value = false }
}
async function completePasswordChange() { const current = (await ElMessageBox.prompt('请输入当前管理员密码完成重新认证。', '修改登录密码', { inputType: 'password', inputPlaceholder: '当前密码', confirmButtonText: '继续', cancelButtonText: '取消', inputValidator: value => Boolean(value?.trim()) || '请输入当前密码' })).value; const next = await ElMessageBox.prompt('首次登录必须设置新密码，至少 12 个字符。', '设置新密码', { inputType: 'password', inputPlaceholder: '新密码（至少 12 个字符）', confirmButtonText: '下一步', cancelButtonText: '取消', inputValidator: value => (value?.length ?? 0) >= 12 || '新密码至少需要 12 个字符' }); const confirmation = await ElMessageBox.prompt('再次输入新密码完成确认。', '确认新密码', { inputType: 'password', inputPlaceholder: '再次输入新密码', confirmButtonText: '保存密码', cancelButtonText: '取消', inputValidator: value => Boolean(value?.trim()) || '请输入确认密码' }); if (next.value !== confirmation.value) throw new Error('两次新密码不一致'); await api('/api/v1/auth/change-password', { method: 'POST', body: JSON.stringify({ current_password: current, new_password: next.value }) }); session.markPasswordChanged(); ElMessage.success('管理员密码已更新') }
async function issueReauthTicket() { const prompt = await ElMessageBox.prompt('输入当前管理员密码生成 5 分钟有效的敏感操作凭证。', '再次验证管理员身份', { inputType: 'password', inputPlaceholder: '当前管理员密码', confirmButtonText: '继续', cancelButtonText: '取消', inputValidator: value => Boolean(value?.trim()) || '请输入当前管理员密码' }); const result = await api<{ reauth_ticket: string }>('/api/v1/auth/reauth', { method: 'POST', body: JSON.stringify({ current_password: prompt.value }) }); return result.reauth_ticket }
async function requirePasswordChange() { if (!session.needsPasswordChange) return true; try { await completePasswordChange(); return true } catch (err) { await session.logout(); if (err === 'cancel') ElMessage.warning('必须完成首次改密后才能使用 Server Panel'); else ElMessage.error(err instanceof Error ? err.message : '首次改密失败'); return false } }
async function submitLogin() { try { await session.login(loginForm.value.username, loginForm.value.password); if (!(await requirePasswordChange())) return; await loadData() } catch (err) { if (session.authenticated) await session.logout(); if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : '登录失败') } }
async function createUser() { if (!newUsername.value.trim()) return; try { const reauthTicket = await issueReauthTicket(); const result = await api<{ initial_password: string }>('/api/v1/admin/users', { method: 'POST', body: JSON.stringify({ username: newUsername.value.trim(), reauth_ticket: reauthTicket }) }); initialPassword.value = result.initial_password; await loadData(); ElMessage.success('用户已创建，初始密码只显示一次') } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : '创建失败') } }
async function toggleUser(user: UserRow) { const next = user.status === 'active' ? 'disabled' : 'active'; try { const reauthTicket = await issueReauthTicket(); await api(`/api/v1/admin/users/${user.id}/status`, { method: 'POST', body: JSON.stringify({ status: next, reauth_ticket: reauthTicket }) }); await loadData(); ElMessage.success(next === 'active' ? '用户已启用' : '用户已停用') } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : '操作失败') } }
async function resetPassword(user: UserRow) { try { const reauthTicket = await issueReauthTicket(); const result = await api<{ initial_password: string }>(`/api/v1/admin/users/${user.id}/reset-password`, { method: 'POST', body: JSON.stringify({ reauth_ticket: reauthTicket }) }); await ElMessageBox.alert(`一次性初始密码：${result.initial_password}`, '密码已重置', { confirmButtonText: '已安全记录', type: 'warning' }); await loadData() } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : '重置失败') } }
async function resetFRPCredential(user: UserRow) { try { const reauthTicket = await issueReauthTicket(); await api(`/api/v1/admin/users/${user.id}/reset-frp-credential`, { method: 'POST', body: JSON.stringify({ reauth_ticket: reauthTicket }) }); await loadData(); ElMessage.success('FRP 凭证已重置，目标用户需要重新登录') } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : 'FRP 凭证重置失败') } }
async function deleteUser(user: UserRow) { try { await ElMessageBox.confirm('删除会撤销所有会话、停止 FRPC，并按顺序清理 Domain、Mapping 和受管 DNS。外部清理失败时本地会保留外部残留记录。', '确认删除用户', { type: 'warning', confirmButtonText: '进入删除流程', cancelButtonText: '取消' }); const reauthTicket = await issueReauthTicket(); await api(`/api/v1/admin/users/${user.id}`, { method: 'DELETE', body: JSON.stringify({ reauth_ticket: reauthTicket }) }); await loadData(); ElMessage.success('用户删除操作已进入补偿队列') } catch { /* cancelled */ } }
async function forceDeleteUser(user: UserRow) { try { await ElMessageBox.confirm('强制删除只移除本地用户和资源；Cloudflare 等外部清理失败会保留残留清单，必须由管理员后续处理。', '确认强制删除', { type: 'warning', confirmButtonText: '强制继续', cancelButtonText: '取消' }); const reauthTicket = await issueReauthTicket(); await api(`/api/v1/admin/users/${user.id}?force=true`, { method: 'DELETE', body: JSON.stringify({ reauth_ticket: reauthTicket }) }); await loadData(); ElMessage.warning('已进入强制补偿流程，请查看操作队列中的外部残留') } catch { /* cancelled */ } }
async function saveCloudflare() { try { const reauthTicket = await issueReauthTicket(); await api('/api/v1/cloudflare/token', { method: 'POST', body: JSON.stringify({ token: cfToken.value, reauth_ticket: reauthTicket }) }); cfToken.value = ''; await loadData(); ElMessage.success('Token 已加密保存，等待权限验证') } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : 'Token 保存失败') } }
async function clearCloudflare() { try { await ElMessageBox.confirm('清除后已有 DNS 记录不会自动删除；未完成的 DNS/证书任务会进入阻塞状态。', '确认清除 Cloudflare Token', { type: 'warning', confirmButtonText: '继续', cancelButtonText: '取消' }); const reauthTicket = await issueReauthTicket(); clearCountdown.value = 3; await new Promise<void>(resolve => { const timer = window.setInterval(() => { clearCountdown.value -= 1; if (clearCountdown.value <= 0) { window.clearInterval(timer); resolve() } }, 1000) }); await api('/api/v1/cloudflare/token', { method: 'DELETE', body: JSON.stringify({ reauth_ticket: reauthTicket }) }); await loadData(); ElMessage.success('Token 已清除') } catch (err) { if (err !== 'cancel') ElMessage.error(err instanceof Error ? err.message : 'Cloudflare Token 清除失败') } finally { clearCountdown.value = 0 } }
async function retryOperation(operation: Operation) { try { await api(`/api/v1/operations/${operation.id}/retry`, { method: 'POST' }); await loadData(); ElMessage.success('操作已重新入队') } catch (err) { ElMessage.error(err instanceof Error ? err.message : '重试失败') } }
function statusLabel(status: string) { return ({ active: 'ACTIVE', disabled: 'DISABLED', pending: 'PENDING', running: 'RUNNING', failed: 'FAILED', succeeded: 'SUCCEEDED' } as Record<string, string>)[status] ?? status.toUpperCase() }
function formatUptime(seconds: number) { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return `${hours}h ${minutes}m` }
function formatTime(value: string) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
onMounted(async () => { await session.restore(); if (session.authenticated && await requirePasswordChange()) await loadData() })
</script>

<template>
  <div v-if="session.loading" class="boot"><div class="boot-mark">FRP<span>/</span>CONTROL</div><div class="boot-line">loading secure control plane</div></div>
  <div v-else-if="!session.authenticated" class="login-shell">
    <div class="login-rail"><div class="brand"><span class="brand-dot"></span><span>FRP / CONTROL</span></div><div class="login-rail-copy"><span class="eyebrow">SERVER PANEL</span><h1>全局资源，<br><em>有据可依。</em></h1><p>面向 FRPS 运维者的控制面。端口租约、配置版本、运行会话与外部操作在同一个审计边界内。</p></div><div class="rail-foot"><span class="live-dot"></span>CONTROL PLANE / v3.0</div></div>
    <main class="login-main"><div class="login-top"><span>SECURE ADMIN ACCESS</span><span class="top-meta">HTTPS · OPAQUE SESSION</span></div><form class="login-card" @submit.prevent="submitLogin"><div class="section-number">01 <span>IDENTITY CHECK</span></div><h2>欢迎回来。</h2><p class="muted">管理员登录仅需要管理员用户名和密码。</p><label>管理员用户名<input v-model="loginForm.username" autocomplete="username" required></label><label>管理员密码<input v-model="loginForm.password" type="password" autocomplete="current-password" required></label><button class="primary-button" type="submit">进入控制面 <ArrowDown :size="16" class="rotate-45" /></button><p v-if="session.error" class="error-text"><WarningFilled :size="15" />{{ session.error }}</p><div class="login-note"><Lock :size="14" /> Server Panel 不连接另一个 Server Panel；连接地址属于部署配置，不在登录页输入。</div></form></main>
  </div>
  <div v-else class="app-shell">
    <aside class="sidebar"><div class="brand"><span class="brand-dot"></span><span>FRP / CONTROL</span></div><div class="side-caption">PUBLIC FRPS CONTROL PLANE</div><nav><button v-for="item in nav" :key="item.id" :class="['nav-item', { active: view === item.id }]" @click="view = item.id"><component :is="item.icon" :size="17" /><span><small>{{ item.kicker }}</small>{{ item.label }}</span><i v-if="view === item.id"></i></button></nav><div class="sidebar-bottom"><div class="frps-pill"><span class="live-dot"></span><div><small>FRPS PUBLIC ENDPOINT</small><strong>{{ stats.frps_public_host || 'not configured' }}:{{ stats.frps_public_port }}</strong></div></div><button class="profile" @click="session.logout"><span class="avatar">{{ session.user?.username?.slice(0, 1).toUpperCase() }}</span><span><strong>{{ session.user?.username }}</strong><small>管理员 · 退出登录</small></span><ArrowDown :size="16" class="profile-arrow" /></button></div></aside>
    <main class="content"><header class="content-header"><div><div class="breadcrumb">SERVER PANEL <span>/</span> {{ activeNav.kicker }}</div><h1>{{ activeNav.label }}</h1></div><div class="header-actions"><span class="sync-state"><span class="live-dot"></span> LIVE · {{ new Date().toLocaleTimeString('zh-CN', { hour12: false }) }}</span><button class="icon-button" aria-label="刷新" @click="loadData"><Refresh :size="17" :class="{ spin: loading }" /></button><button class="icon-button" aria-label="通知"><Bell :size="17" /></button></div></header>
      <section v-if="view === 'overview'" class="view"><div class="hero-strip"><div><span class="eyebrow">SYSTEM POSTURE / {{ new Date().toLocaleDateString('zh-CN') }}</span><h2>控制面运行平稳<span class="accent-dot">.</span></h2><p>所有资源在 Server Panel 内完成权威判定。观察状态与期望配置分开显示。</p></div><div class="hero-code"><span>UPTIME</span><strong>{{ formatUptime(stats.server_uptime_seconds) }}</strong><small>since last boot</small></div></div><div class="metric-grid"><article class="metric"><div class="metric-label"><User :size="15" /> ACTIVE USERS</div><strong>{{ stats.active_users }}</strong><span class="metric-note green">identity boundary healthy</span></article><article class="metric"><div class="metric-label"><Files :size="15" /> MANAGED MAPPINGS</div><strong>{{ stats.mappings }}</strong><span class="metric-note">port leases remain authoritative</span></article><article class="metric"><div class="metric-label"><Clock :size="15" /> PENDING OPERATIONS</div><strong>{{ stats.pending }}</strong><span class="metric-note amber">awaiting client or provider</span></article><article class="metric"><div class="metric-label"><WarningFilled :size="15" /> CONFIG ERRORS</div><strong :class="{ danger: stats.errors > 0 }">{{ stats.errors }}</strong><span class="metric-note" :class="stats.errors ? 'red' : 'green'">{{ stats.errors ? 'needs attention' : 'no active errors' }}</span></article></div><div class="split-grid"><section class="panel panel-table"><div class="panel-head"><div><span class="eyebrow">RECENT ACTIVITY</span><h3>操作队列</h3></div><button class="text-button" @click="view = 'operations'">查看全部 <ArrowDown :size="14" class="rotate-45" /></button></div><table><thead><tr><th>类型</th><th>阶段</th><th>状态</th><th>创建时间</th></tr></thead><tbody><tr v-for="op in operations.slice(0, 5)" :key="op.id"><td><strong>{{ op.operation_type }}</strong><small class="mono">{{ op.id.slice(0, 12) }}</small></td><td>{{ op.phase }} / {{ op.step }}</td><td><span :class="['status', op.status]">{{ statusLabel(op.status) }}</span></td><td class="muted">{{ formatTime(op.created_at) }}</td></tr><tr v-if="!operations.length"><td colspan="4" class="empty">还没有跨系统操作记录。</td></tr></tbody></table></section><section class="panel posture"><div class="panel-head"><div><span class="eyebrow">BOUNDARY CHECK</span><h3>系统边界</h3></div><CircleCheckFilled class="ok-icon" :size="20" /></div><div class="boundary-row"><span>Session service</span><strong>opaque / active</strong></div><div class="boundary-row"><span>Storage</span><strong>SQLite WAL / FULL</strong></div><div class="boundary-row"><span>FRPS address</span><strong>{{ stats.frps_public_host }}:{{ stats.frps_public_port }}</strong></div><div class="boundary-row"><span>Control route</span><strong>separate</strong></div><div class="boundary-row"><span>External provider</span><strong :class="cfStatus.configured ? 'green' : 'amber'">{{ cfStatus.configured ? cfStatus.status : 'not configured' }}</strong></div></section></div></section>
      <section v-else-if="view === 'users'" class="view"><div class="toolbar"><div><span class="eyebrow">IDENTITY / ACCESS</span><p class="view-intro">普通用户只能看到自己的 Mapping、Domain、Operation 与运行状态。每个用户同一时间只保留一个 Client Session。</p></div><button class="primary-button compact" @click="showCreateUser = true"><Plus :size="16" /> 创建用户</button></div><section class="panel panel-table"><table><thead><tr><th>用户</th><th>状态</th><th>配置进度</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><div class="user-cell"><span class="avatar small">{{ user.username.slice(0,1).toUpperCase() }}</span><div><strong>{{ user.username }}</strong><small class="mono">{{ user.id.slice(0, 14) }}</small></div></div></td><td><span :class="['status', user.status]">{{ statusLabel(user.status) }}</span></td><td><div class="progress-cell"><span>{{ user.applied_config_version }} / {{ user.desired_config_version }}</span><div class="progress"><i :style="{ width: `${user.desired_config_version ? Math.min(100, user.applied_config_version / user.desired_config_version * 100) : 100}%` }"></i></div></div></td><td class="muted">{{ formatTime(user.created_at) }}</td><td><div class="table-actions"><template v-if="user.status !== 'deleting'"><button class="text-button" @click="toggleUser(user)">{{ user.status === 'active' ? '停用' : '启用' }}</button><button class="text-button" @click="resetPassword(user)">重置密码</button><button class="text-button danger" @click="deleteUser(user)">删除</button></template><button v-else class="text-button danger" @click="forceDeleteUser(user)">强制完成</button></div></td></tr></tbody></table></section></section>
      <section v-else-if="view === 'operations'" class="view"><div class="toolbar"><div><span class="eyebrow">LONG-RUNNING WORK</span><p class="view-intro">外部 Provider、Client 应用、Router 和删除补偿都必须有明确步骤；失败不会被渲染成成功。</p></div></div><section class="panel panel-table"><table><thead><tr><th>Operation</th><th>类型</th><th>阶段 / 步骤</th><th>状态</th><th>时间</th><th>动作</th></tr></thead><tbody><tr v-for="op in operations" :key="op.id"><td class="mono">{{ op.id.slice(0, 16) }}</td><td><strong>{{ op.operation_type }}</strong><small class="mono">{{ op.error_code || op.compensation_status || 'no error' }}</small></td><td>{{ op.phase }} / {{ op.step }}<small v-if="op.error_message">{{ op.error_message }}</small><small v-if="op.external_residue_count">外部残留：{{ op.external_residue_count }} 项</small><small v-for="residue in op.external_residues" :key="`${op.id}-${residue.identifier}`" class="residue-line">{{ residue.provider }} · {{ residue.identifier }} · {{ residue.reason }}</small></td><td><span :class="['status', op.status]">{{ statusLabel(op.status) }}</span></td><td class="muted">{{ formatTime(op.created_at) }}</td><td><button v-if="['failed', 'canceled'].includes(op.status)" class="text-button" @click="retryOperation(op)">重试</button><span v-else class="muted">—</span></td></tr><tr v-if="!operations.length"><td colspan="6" class="empty">队列为空，系统没有隐式后台工作。</td></tr></tbody></table></section></section>
      <section v-else-if="view === 'cloudflare'" class="view"><div class="provider-header"><div><span class="eyebrow">EDGE PROVIDER / SECRET BOUNDARY</span><h2>Cloudflare Token</h2><p class="view-intro">Token 只在 Server Panel 加密保存。Client Panel 不会接触它；此页面也不显示明文。</p></div><div :class="['provider-state', cfStatus.status]"><span class="live-dot"></span><strong>{{ cfStatus.configured ? statusLabel(cfStatus.status) : 'MISSING' }}</strong><small>{{ cfStatus.verified_at ? `verified ${formatTime(cfStatus.verified_at)}` : 'permission verification pending' }}</small></div></div><div class="provider-grid"><section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">PENDING VERSION</span><h3>上传或替换</h3></div><Key :size="20" /></div><label>Cloudflare API Token<input v-model="cfToken" type="password" autocomplete="off" placeholder="粘贴后只留在当前请求内"></label><p class="form-hint">权限验证会分别检查 Token、Zone Read、DNS Read；DNS Write 不执行破坏性探测，实际写入失败会保持错误并支持重试。</p><div v-if="cfStatus.capabilities?.missing?.length" class="permission-warning">缺失权限：{{ cfStatus.capabilities.missing.join('、') }}</div><button class="primary-button compact" :disabled="!cfToken" @click="saveCloudflare">加密保存并验证 <ArrowDown :size="14" class="rotate-45" /></button></section><section class="panel danger-panel"><div class="panel-head"><div><span class="eyebrow">DESTRUCTIVE ACTION</span><h3>清除 Token</h3></div><WarningFilled class="danger-icon" :size="20" /></div><p>清除不会删除已经存在的 Cloudflare DNS。未执行的 DNS/ACME 任务会阻塞并等待新 Token。</p><button class="danger-button" :disabled="!cfStatus.configured || clearCountdown > 0" @click="clearCloudflare">{{ clearCountdown ? `等待 ${clearCountdown}s…` : '清除 Cloudflare Token' }}</button></section></div></section>
      <section v-else class="view"><div class="system-grid"><section class="panel system-card"><span class="eyebrow">RELEASE CONTRACT</span><h3>双发行物</h3><p>Server Panel 与 Client Panel 独立构建、独立部署，不共享业务数据库。</p><div class="code-row"><span>server</span><strong>Go / SQLite WAL / Router</strong></div><div class="code-row"><span>client</span><strong>Go / FRPC Supervisor</strong></div><div class="code-row"><span>protocol</span><strong>REST v1 + WebSocket</strong></div></section><section class="panel system-card"><span class="eyebrow">SECURITY MATERIAL</span><h3>密钥用途隔离</h3><p>在线主密钥、配置签名密钥、Router Snapshot 密钥、证书包装密钥和备份 KDF 上下文分开。</p><div class="key-list"><span><Key :size="14" /> server_master_key</span><span><Lock :size="14" /> config_signing_key</span><span><Lock :size="14" /> certificate_wrapping_key</span><span><Files :size="14" /> backup_kdf_context</span></div></section></div></section>
      <section v-if="view === 'users'" class="panel form-panel credential-panel"><div class="panel-head"><div><span class="eyebrow">CREDENTIAL LIFECYCLE</span><h3>重置用户 FRP 凭证</h3></div><Lock :size="20" /></div><label>目标用户<select v-model="selectedFRPUserID"><option value="" disabled>选择需要重置的用户</option><option v-for="user in users.filter(item => item.role === 'user' && item.status !== 'deleted')" :key="user.id" :value="user.id">{{ user.username }} · {{ user.status }} · FRP v{{ user.frp_credential.secret_version }}</option></select></label><p class="form-hint">状态：{{ selectedFRPUser?.frp_credential.status ?? 'unknown' }} · Secret Version：v{{ selectedFRPUser?.frp_credential.secret_version ?? 0 }} · 最近重置：{{ selectedFRPUser?.frp_credential.rotated_at ? formatTime(selectedFRPUser.frp_credential.rotated_at) : '未重置' }}。需要当前管理员密码二次认证。旧 Secret、Session 和 generation 会立即失效；新 Secret 不会在管理员面板展示。</p><button class="danger-button" :disabled="!selectedFRPUserID" @click="resetFRPCredential(users.find(item => item.id === selectedFRPUserID)!)">重置 FRP 凭证并要求重新登录</button></section>
    </main>
    <el-dialog v-model="showCreateUser" title="创建普通用户" width="420px" class="dark-dialog"><label>用户名<input v-model="newUsername" placeholder="例如: ops-alice" @keyup.enter="createUser"></label><p v-if="initialPassword" class="password-reveal">一次性初始密码：<code>{{ initialPassword }}</code><small>只显示本次，请通过受保护渠道交付。</small></p><template #footer><button class="text-button" @click="showCreateUser = false">取消</button><button class="primary-button compact" @click="createUser">创建用户</button></template></el-dialog>
  </div>
</template>
