import { ref } from 'vue'
import { defineStore } from 'pinia'
import { api, setCSRFToken } from '../api'

export type Mapping = { id: string; name: string; proxy_type: 'tcp' | 'udp' | 'http'; lifecycle_status: string; desired_state: string; observed_state: string; revision: number; local_ip: string; local_port: number; remote_port?: number }
export type Domain = { id: string; mapping_id: string; hostname: string; normalized_domain: string; https_mode: string; http_redirect: boolean; dns_type: 'A' | 'AAAA' | 'CNAME'; dns_content: string; dns_ttl: number; dns_proxied: boolean; dns_managed_by_panel: boolean; dns_adopted: boolean; status: string; revision: number }
export type FRPCredentialStatus = { present: boolean; secret_version: number; rotated_at?: string; status: string }
export type Dashboard = { user: { username: string; must_change_password: boolean }; desired_config_version: number; applied_config_version: number; observed_client_status: string; frp_credential: FRPCredentialStatus; mappings: Mapping[]; counts: { total_mappings: number; running: number; pending: number; offline: number; errors: number } }
export type Operation = { id: string; operation_type: string; resource_type: string; resource_id?: string; status: string; phase: string; step: string; error_code?: string; error_message?: string; compensation_status?: string; external_residue_count?: number; external_residues?: Array<{ provider: string; identifier: string; reason: string }>; created_at: string; updated_at?: string }
export type CertificateInfo = { server_panel_url: string; transport: string; verified: boolean; verification_error?: string; subject?: string; issuer?: string; not_before?: string; not_after?: string; spki_sha256?: string; dns_names?: string[]; ip_addresses?: string[] }

export const useClientStore = defineStore('client', () => {
  const authenticated = ref(false); const loading = ref(true); const user = ref<{ username: string; must_change_password: boolean } | null>(null); const serverURL = ref(''); const csrf = ref(''); const dashboard = ref<Dashboard | null>(null); const domains = ref<Domain[]>([]); const operations = ref<Operation[]>([]); const localStatus = ref<Record<string, unknown>>({}); const error = ref('')
  async function restore() { try { const session = await api<{ user: typeof user.value; server_panel_url: string; csrf_token: string }>('/api/v1/session'); authenticated.value = true; user.value = session.user; serverURL.value = session.server_panel_url; csrf.value = session.csrf_token; setCSRFToken(csrf.value); if (!user.value?.must_change_password) await refresh() } catch { authenticated.value = false; setCSRFToken('') } finally { loading.value = false } }
  async function inspectServer(serverPanelURL: string) { return api<CertificateInfo>('/api/v1/server/inspect', { method: 'POST', body: JSON.stringify({ server_panel_url: serverPanelURL }) }) }
  async function login(payload: { server_panel_url: string; username: string; password: string; trusted_spki_sha256?: string }) { error.value = ''; const session = await api<{ user: typeof user.value; server_panel_url: string; csrf_token: string }>('/api/v1/login', { method: 'POST', body: JSON.stringify(payload) }); authenticated.value = true; user.value = session.user; serverURL.value = session.server_panel_url; csrf.value = session.csrf_token; setCSRFToken(csrf.value); localStorage.setItem('last_server_panel_url', session.server_panel_url) }
  async function changePassword(currentPassword: string, newPassword: string) { await api('/api/v1/password', { method: 'POST', body: JSON.stringify({ current_password: currentPassword, new_password: newPassword }) }); if (user.value) user.value = { ...user.value, must_change_password: false } }
  async function logout() { await api('/api/v1/logout', { method: 'POST' }).catch(() => undefined); authenticated.value = false; user.value = null; dashboard.value = null; domains.value = []; operations.value = []; csrf.value = ''; setCSRFToken('') }
  async function resetFRPCredential(currentPassword: string) { await api('/api/v1/frp-credential/reset', { method: 'POST', body: JSON.stringify({ current_password: currentPassword }) }); authenticated.value = false; user.value = null; dashboard.value = null; domains.value = []; operations.value = []; csrf.value = ''; setCSRFToken('') }
  async function refresh() { const [nextDashboard, domainResponse, operationResponse, nextLocalStatus] = await Promise.all([api<Dashboard>('/api/v1/dashboard'), api<{ items: Domain[] }>('/api/v1/domains'), api<{ items: Operation[] }>('/api/v1/operations'), api<Record<string, unknown>>('/api/v1/local-status')]); dashboard.value = nextDashboard; domains.value = domainResponse.items; operations.value = operationResponse.items; localStatus.value = nextLocalStatus }
  async function retryOperation(operationID: string) { await api(`/api/v1/operations/${operationID}/retry`, { method: 'POST' }); await refresh() }
  return { authenticated, loading, user, serverURL, csrf, dashboard, domains, operations, localStatus, error, restore, inspectServer, login, changePassword, logout, resetFRPCredential, refresh, retryOperation }
})
